baseURL = "https://irscript.github.io/"
canonifyURLs = true 
relativeURLs = true 
uglyURLs = false  

languageCode = 'zh-CN'
defaultContentLanguage = "zh-CN" 

theme = "hugo-theme-relearn"
title = "巨人之海"

[outputs]
    home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
    section = ["HTML", "RSS", "PRINT"]
    page = ["HTML", "RSS", "PRINT"]

[markup]
    [markup.highlight]
        lineNumbersInTable = false
        guessSyntax = false
        noClasses = false
        # style = "tango"
    [markup.goldmark.renderer]
        unsafe = true

[languages]
    [languages.zh-cn]
        title = "巨人之海"
        weight = 0
        languageName = "简体中文"
        #contentDir = "content/"

        [languages.zh-cn.params]
            landingPageName = "<i class='fas fa-home'></i> 主页"

        [[languages.zh-cn.menu.shortcuts]]
            name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
            identifier = "ds"
            url = "https://github.com/irscript/irscript.github.io"
            weight = 10

        [[languages.zh-cn.menu.shortcuts]]
            name = "<i class='fas fa-fw fa-bookmark'></i> Hugo 文档"
            identifier = "hugodoc"
            url = "https://gohugo.io/"
            weight = 20

        [[languages.zh-cn.menu.shortcuts]]
            name = "<i class='fas fa-fw fa-tags'></i> 标签"
            pageRef = "tags/"
            weight = 30

[params]
    alwaysopen = false
    editURL = "https://github.com/irscript/irscript.github.io/content/"
    description = "站在巨人的肩膀上"
    author = "月明之都"
    showVisitedLinks = true
    collapsibleMenu = true
    disableBreadcrumb = false
    disableInlineCopyToClipBoard = true
    disableNextPrev = false
    disableLandingPageButton = true
    breadcrumbSeparator = ">"
    titleSeparator = "::"
    themeVariant = [ "auto", "relearn-bright", "relearn-light", "relearn-dark", "zen-light", "zen-dark", "neon", "learn", "blue", "green", "red" ]
    themeVariantAuto = [ "neon","relearn-light", "relearn-dark" ]
    disableSeoHiddenPages = true
    # this is to index search for your native language in other languages, too (eg.
    # pir in this showcase)
    additionalContentLanguage = [ "zh-cn" ]
    # this is for the stylesheet generator to allow for interactivity in Mermaid
    # graphs; you usually will not need it and you should remove this for
    # security reasons
    mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
    mermaidZoom = true
    [params.siteparam.test]
        text = "A **nested** parameter <b>with</b> formatting"
    [params.imageEffects]
        bg-white = true # extension, not supported by the theme
        border = true